export const REMIND_BEFORE_DAYS = 3; // Default reminder days before renewal date
export const PAGE_LIMIT = 10;
export const PAYMENT_PROVIDERS = [
  "STRIPE",
  "PAYPAL",
  "BRAINTREE",
  "ADYEN",
  "TWO_CHECKOUT",
  "WORLDPAY",
  "PAYONEER",
  "APPLE_PAY",
  "GOOGLE_PAY",
  "ALIPAY",
  "WECHAT_PAY",
  "WISE",
] as const;
export const PAYMENT_STATUSES = ["PENDING", "SUCCESS", "FAILED"] as const;
export const CURRENCIES = [
  "USD",
  "EUR",
  "GBP",
  "JPY",
  "AUD",
  "CAD",
  "CHF",
  "CNY",
  "INR",
  "NZD",
  "SGD",
  "ZAR",
  "HKD",
  "NOK",
  "SEK",
  "DKK",
  "MXN",
  "BRL",
  "RUB",
  "KRW",
  "AED",
  "SAR",
  "BDT",
] as const;
