GET http://localhost:8000

###
POST http://localhost:8000/api/auth/sign-up/email
Content-Type: application/json

{
  "name": "SubSavver",
  "email": "subsavver@gmail.com",
  "password": "subsavver123"
}
